services:
  - type: web
    name: forensic-ai-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATASET_PATH
        value: ./datasets
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
