from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO
import json
from datetime import datetime

def generate_pdf_report(report_data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = styles['Title']
    story.append(Paragraph(f"Forensic Analysis Report: {report_data['id']}", title_style))
    story.append(Spacer(1, 12))

    # Meta Info
    normal_style = styles['Normal']
    timestamp = report_data.get('timestamp', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    story.append(Paragraph(f"<b>Date:</b> {timestamp}", normal_style))
    story.append(Paragraph(f"<b>Type:</b> {report_data['scan_type'].upper()}", normal_style))
    story.append(Paragraph(f"<b>Target:</b> {report_data['input_summary']}", normal_style))
    
    threat_status = "THREAT DETECTED" if report_data['is_threat'] else "SAFE"
    threat_color = "red" if report_data['is_threat'] else "green"
    story.append(Paragraph(f"<b>Status:</b> <font color='{threat_color}'>{threat_status}</font>", normal_style))
    
    if report_data.get('confidence'):
        story.append(Paragraph(f"<b>Threat Score:</b> {report_data['confidence']}%", normal_style))
        
    story.append(Spacer(1, 24))

    # Details Section
    story.append(Paragraph("Analysis Details", styles['Heading2']))
    story.append(Spacer(1, 12))

    details_raw = report_data.get('details')
    if details_raw:
        try:
            # If details is a string, parse it. If it's already a dict (from recent fetch), use it.
            if isinstance(details_raw, str):
                details = json.loads(details_raw)
            else:
                details = details_raw
                
            # Flatten details for table
            table_data = [['Parameter', 'Value']]
            
            def add_to_table(obj, prefix=''):
                if isinstance(obj, dict):
                    for k, v in obj.items():
                        if isinstance(v, (dict, list)):
                            add_to_table(v, prefix + k + ' -> ')
                        else:
                            table_data.append([prefix + k, str(v)])
                elif isinstance(obj, list):
                    for i, item in enumerate(obj):
                        add_to_table(item, prefix + f'[{i}] ')
            
            add_to_table(details)
            
            # Create Table
            t = Table(table_data, colWidths=[3*inch, 3.5*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('WORDWRAP', (0, 0), (-1, -1), 'CJK'), # Allow wrapping
            ]))
            story.append(t)
            
        except Exception as e:
            story.append(Paragraph(f"Error parsing details: {str(e)}", normal_style))
            story.append(Paragraph(f"Raw Data: {str(details_raw)}", normal_style))
    else:
        story.append(Paragraph("No detailed analysis data available.", normal_style))

    # Footer
    story.append(Spacer(1, 48))
    story.append(Paragraph("Generated by Forensic AI Hub", styles['Italic']))

    doc.build(story)
    buffer.seek(0)
    return buffer
